Color = input("Pick a color: ")
Number = input("Pick a number: ")
Animal = input("Pick an animal: ")
Job = input("Pick a job: ")
Name = input("Pick a name: ")
place = input("Pick a place: ")
activity = input("Pick an activity: ")
print("The", Color, Number, "year old", Animal, "was a", Job, "with", Name, "at", place, "and liked", activity, ".")